# Generated by Django 3.1.7 on 2021-03-04 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
