# Generated by Django 3.1.7 on 2021-03-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='user',
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Общая цена'),
        ),
    ]
