# Generated by Django 3.1.7 on 2021-03-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210305_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Общая стоимость'),
        ),
    ]
