# Generated by Django 3.1.7 on 2021-03-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210311_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='finished',
            field=models.BooleanField(blank=True, default=False, verbose_name='Завершён'),
        ),
    ]
