# Generated by Django 3.1.7 on 2021-03-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_cart_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_products',
            field=models.PositiveIntegerField(default=0, verbose_name='Товаров'),
        ),
    ]
