# Generated by Django 3.1.7 on 2021-03-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210311_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='in_order',
        ),
    ]
