# Generated by Django 3.1.7 on 2021-03-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_carouselcategory_carouselimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimages',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активное'),
        ),
    ]
